name: trip_sage
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^4.11.0
  firebase_auth: ^6.5.3
  cloud_firestore: ^6.6.0
  cloud_functions: ^6.3.3
  flutter_riverpod: ^3.3.2
  go_router: ^17.3.0
  google_maps_flutter: ^2.17.1
  fl_chart: ^1.2.0
  google_fonts: ^8.1.0
  flutter_native_splash: ^2.4.8
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/

flutter_native_splash:
  color: "#F7F9F9"
  color_dark: "#1A2B2B"
  image: assets/icon.png
  image_dark: assets/icon.png
  android_12:
    color: "#F7F9F9"
    color_dark: "#1A2B2B"
    image: assets/icon.png
    image_dark: assets/icon.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/icon.png"