// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZjCdFRiSZDqSJ2OUYIpoSECHYk5n-cYQ',
    appId: '1:874499212861:web:bd5352e26e036f056ecc54',
    messagingSenderId: '874499212861',
    projectId: 'trip-sage-e2g0i2t',
    authDomain: 'trip-sage-e2g0i2t.firebaseapp.com',
    storageBucket: 'trip-sage-e2g0i2t.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0VtETD1MznS1pPzDsDngRgVrXSnphV3c',
    appId: '1:874499212861:android:a0790022ed7347906ecc54',
    messagingSenderId: '874499212861',
    projectId: 'trip-sage-e2g0i2t',
    storageBucket: 'trip-sage-e2g0i2t.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcJqxARpR9DpdEPtp5vnnY5bNl6biz_Hc',
    appId: '1:874499212861:ios:308eef1a0db21eff6ecc54',
    messagingSenderId: '874499212861',
    projectId: 'trip-sage-e2g0i2t',
    storageBucket: 'trip-sage-e2g0i2t.firebasestorage.app',
    iosBundleId: 'com.example.tripSage',
  );
}
